version: '3.8'

services:
  blog:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/blogdb
    depends_on:
      - mongo

  test:
    build: .
    command: ["npm", "test"]
    environment:
      - NODE_ENV=test
      - MONGO_URI=mongodb://mongo:27017/blogdb
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: